### ISSUE TITLE
work on windows x64

### ISSUE THREAD

**Issue by caffeTao** [Lupino/huabot-brain#1]
I've find a windows x64 version of caffe, and it does work with training, but i  don't know how to compile the python and matlab wrapper, and i find your project here for some help, so ,will there be a windows x64 version of your project released? If necessary, this is the windows version caffe-master https://github.com/initialneil/caffe/tree/windows

**Comment by Lupino** [comment]
Maybe can compile caffe on windows using [mingw](http://www.mingw.org/) or [cygwin](http://www.cygwin.com/).
