### ISSUE TITLE
github.com/Lupino/huabot-brain/tools/train_worker error 404

### ISSUE THREAD

**Issue by wuhang** [Lupino/huabot-brain#3]
Hello where is train_worker?
github.com/Lupino/huabot-brain (download)
package github.com/Lupino/huabot-brain/tools/train_worker
    imports github.com/Lupino/huabot-brain/tools/train_worker
    imports github.com/Lupino/huabot-brain/tools/train_worker: cannot find package "github.com/Lupino/huabot-brain/tools/train_worker" in any of:
    /usr/lib/go/src/pkg/github.com/Lupino/huabot-brain/tools/train_worker (from $GOROOT)
    /home/wuhang/gopath/src/github.com/Lupino/huabot-brain/tools/train_worker (from $GOPATH)

**Comment by Lupino** [comment]
I update the repo and remove the train worker, please update it
