### ISSUE TITLE
Hi，I met an error called "grep:resources/logs/caffe. INFO no such file or directory"

### ISSUE THREAD

**Issue by WyHy** [Lupino/huabot-brain#4]
I install the huabot-brain by the instruction listed above, the command huabot-brain seems work without errors, but when I open the page 127.0.0.1:3000,the terminal says :::grep:resources/logs/caffe. INFO no such file or directory, and the solve button not worked with the same error tip, can you tell me how to solve this error, thank you

**Comment by Lupino** [comment]
There is no a real error.

you train and caffe will create the log caffe.INFO
